// Interface copy for the CV editor. Structural metadata (input types, list parsing,
// layout) stays in editor.js; only human-facing text lives here.
export const EDITOR_COPY = Object.freeze({
  id: {
    stepCounter: "Langkah {index} dari {total}",
    tipTitle: "Contoh panduan",
    validationTitle: "{count} hal perlu diperbaiki",
    validationBody: "Periksa field bertanda merah sebelum melanjutkan.",
    previous: "Sebelumnya",
    next: "Simpan dan lanjut",
    review: "Tinjau CV",
    entryUp: "Naik",
    entryDown: "Turun",
    entryDuplicate: "Duplikat",
    entryRemove: "Hapus",
    entryCount: "{count} entri",
    entryEmpty: "Belum ada entri",
    collectionEmpty: "Tambahkan {singular} jika relevan dengan posisi tujuan.",
    optionalIntro: "Bagian berikut opsional. Tambahkan hanya yang membantu membuktikan kecocokan Anda.",
    bulletQuality: "{strong} dari {total} bullet memuat aksi, konteks, dan ukuran.",
    summaryLabel: "Ringkasan profesional",
    summaryPlaceholder: "Jelaskan bidang, pengalaman, keahlian utama, dan nilai yang Anda berikan.",
    summaryMeta: "Target 300–500 karakter; maksimum 700.",
    steps: {
      basics: { label: "Data diri", description: "Informasi utama agar recruiter dapat mengenali dan menghubungi Anda.", example: "Gunakan jabatan yang umum, misalnya Cloud Engineer, bukan Cloud Ninja." },
      summary: { label: "Ringkasan", description: "Rangkum keahlian, konteks pengalaman, dan nilai utama Anda.", example: "Targetkan 3–4 kalimat yang relevan dengan posisi tujuan." },
      experience: { label: "Pengalaman", description: "Utamakan pengalaman terbaru dan hasil yang dapat dibuktikan.", example: "Rumus bullet: kata kerja aksi + konteks + dampak atau ukuran." },
      education: { label: "Pendidikan", description: "Tambahkan pendidikan formal yang paling relevan.", example: "Tuliskan gelar, bidang studi, institusi, dan periode secara konsisten." },
      skills: { label: "Keterampilan", description: "Kelompokkan hard skills agar mudah dipindai recruiter dan ATS.", example: "Contoh kelompok: Cloud, Automation, Observability, atau Security." },
      extras: { label: "Tambahan", description: "Aktifkan bagian opsional yang benar-benar mendukung posisi target.", example: "Proyek dan sertifikasi sering lebih berguna daripada daftar minat umum." },
    },
    basics: {
      fullName: { label: "Nama lengkap", placeholder: "Dina Pratama" },
      headline: { label: "Jabatan saat ini / target", placeholder: "Cloud Engineer" },
      email: { label: "Email", placeholder: "nama@example.com" },
      phone: { label: "Nomor telepon", placeholder: "+62 812 3456 7890" },
      location: { label: "Lokasi", placeholder: "Jakarta, Indonesia" },
    },
    collections: {
      links: {
        title: "Tautan profesional", singular: "tautan", add: "Tambah tautan",
        fields: { label: { label: "Label", placeholder: "LinkedIn" }, url: { label: "URL", placeholder: "https://linkedin.com/in/nama" } },
      },
      experience: {
        title: "Pengalaman kerja", singular: "pengalaman", add: "Tambah pengalaman",
        fields: {
          role: { label: "Jabatan", placeholder: "Cloud Engineer" },
          organization: { label: "Perusahaan / organisasi", placeholder: "Nama perusahaan" },
          location: { label: "Lokasi", placeholder: "Jakarta atau Remote" },
          startDate: { label: "Mulai" },
          endDate: { label: "Selesai" },
          current: { label: "Saya masih bekerja di sini" },
          bullets: { label: "Pencapaian dan tanggung jawab", placeholder: "Satu bullet per baris", help: "Mulai dengan aksi, lalu jelaskan konteks dan dampak yang benar-benar terjadi." },
        },
      },
      education: {
        title: "Pendidikan", singular: "pendidikan", add: "Tambah pendidikan",
        fields: {
          qualification: { label: "Gelar / kualifikasi", placeholder: "Sarjana Teknik Informatika" },
          field: { label: "Bidang studi", placeholder: "Teknik Informatika" },
          institution: { label: "Institusi", placeholder: "Nama universitas" },
          location: { label: "Lokasi", placeholder: "Bandung" },
          startDate: { label: "Mulai" },
          endDate: { label: "Selesai" },
          bullets: { label: "Detail relevan", placeholder: "Prestasi, konsentrasi, atau aktivitas relevan — satu per baris" },
        },
      },
      skills: {
        title: "Kelompok keterampilan", singular: "kelompok keterampilan", add: "Tambah kelompok",
        fields: {
          name: { label: "Nama kelompok", placeholder: "Cloud" },
          items: { label: "Keterampilan", placeholder: "AWS, Amazon EKS, Terraform", help: "Pisahkan dengan koma dan masukkan hanya keterampilan yang benar-benar Anda kuasai." },
        },
      },
      projects: {
        title: "Proyek", singular: "proyek", add: "Tambah proyek",
        fields: {
          name: { label: "Nama proyek", placeholder: "Landing Zone AWS" },
          role: { label: "Peran", placeholder: "Cloud Engineer" },
          startDate: { label: "Mulai" },
          endDate: { label: "Selesai" },
          url: { label: "URL", placeholder: "https://…" },
          bullets: { label: "Kontribusi dan hasil", placeholder: "Satu bullet per baris", help: "Jelaskan kontribusi Anda, teknologi yang dipakai, dan hasilnya." },
        },
      },
      certifications: {
        title: "Sertifikasi", singular: "sertifikasi", add: "Tambah sertifikasi",
        fields: {
          name: { label: "Nama sertifikasi", placeholder: "AWS Certified Solutions Architect — Associate" },
          issuer: { label: "Penerbit", placeholder: "Amazon Web Services" },
          date: { label: "Tanggal terbit" },
          credentialId: { label: "Credential ID", placeholder: "Opsional" },
          url: { label: "URL verifikasi", placeholder: "https://…" },
        },
      },
      languages: {
        title: "Bahasa", singular: "bahasa", add: "Tambah bahasa",
        fields: {
          name: { label: "Bahasa", placeholder: "English" },
          proficiency: { label: "Tingkat", placeholder: "Professional working proficiency" },
        },
      },
      awards: {
        title: "Penghargaan", singular: "penghargaan", add: "Tambah penghargaan",
        fields: {
          title: { label: "Judul", placeholder: "Employee Excellence Award" },
          issuer: { label: "Pemberi", placeholder: "Nama organisasi" },
          date: { label: "Tanggal" },
          description: { label: "Keterangan", placeholder: "Alasan atau konteks penghargaan" },
        },
      },
      volunteering: {
        title: "Pengalaman relawan", singular: "pengalaman relawan", add: "Tambah pengalaman relawan",
        fields: {
          role: { label: "Peran", placeholder: "Mentor Cloud" },
          organization: { label: "Organisasi", placeholder: "Komunitas teknologi" },
          startDate: { label: "Mulai" },
          endDate: { label: "Selesai" },
          bullets: { label: "Kontribusi", placeholder: "Satu bullet per baris" },
        },
      },
    },
    letter: {
      eyebrow: "Dokumen kedua",
      title: "Surat Lamaran",
      intro: "Surat pendamping CV. Isinya menjelaskan alasan Anda melamar dan bukti pengalaman yang paling relevan dengan posisi target.",
      tip: "Tiga paragraf sudah cukup: alasan melamar, bukti pengalaman dengan angka, lalu penutup. Hindari mengulang seluruh isi CV.",
      reusedTitle: "Dipakai ulang, tidak perlu diisi dua kali",
      statusFilled: "Terisi",
      statusMissing: "Belum ada",
      statusOptional: "Opsional",
      fillNow: "Isi sekarang",
      signerLabel: "Nama penanda tangan",
      signerHint: "Diambil dari langkah Data diri",
      roleLabel: "Posisi yang dilamar",
      roleHint: "Diisi di panel Sesuai lowongan",
      companyLabel: "Perusahaan tujuan",
      companyHint: "Opsional, diisi di panel Sesuai lowongan",
      paragraphMeta: "{paragraphs} paragraf · {words} kata",
      lengthHint: "Panjang ideal 200–350 kata agar tetap satu halaman.",
      bodyHelp: "Satu paragraf per baris. Biarkan satu baris kosong agar lebih mudah dibaca.",
      fields: {
        recipient: { label: "Penerima", placeholder: "Bapak/Ibu Tim Rekrutmen" },
        recipientTitle: { label: "Jabatan penerima", placeholder: "Opsional, misalnya Talent Acquisition" },
        city: { label: "Kota", placeholder: "Jakarta" },
        date: { label: "Tanggal surat", help: "Kosongkan jika ingin mengisi tanggal secara manual saat mengirim." },
        greeting: { label: "Sapaan", placeholder: "Dengan hormat," },
        closing: { label: "Penutup", placeholder: "Hormat saya," },
        paragraphs: { label: "Isi surat" },
      },
      example: [
        "Melalui surat ini saya mengajukan diri untuk posisi Cloud Engineer di perusahaan Bapak/Ibu.",
        "",
        "Selama tiga tahun terakhir saya membangun dan mengoperasikan platform AWS, termasuk menstandarkan deployment 25 workload melalui Terraform sehingga waktu rilis turun 40%.",
        "",
        "Saya siap mendiskusikan bagaimana pengalaman ini dapat mendukung target teknologi perusahaan. Terima kasih atas waktu dan pertimbangannya.",
      ].join("\n"),
    },
  },
  en: {
    stepCounter: "Step {index} of {total}",
    tipTitle: "Guidance",
    validationTitle: "{count} things need fixing",
    validationBody: "Check the fields marked in red before moving on.",
    previous: "Back",
    next: "Save and continue",
    review: "Review CV",
    entryUp: "Up",
    entryDown: "Down",
    entryDuplicate: "Duplicate",
    entryRemove: "Remove",
    entryCount: "{count} entries",
    entryEmpty: "No entries yet",
    collectionEmpty: "Add a {singular} if it is relevant to the role you want.",
    optionalIntro: "The sections below are optional. Add only what helps prove you fit the role.",
    bulletQuality: "{strong} of {total} bullets carry an action, context, and a measure.",
    summaryLabel: "Professional summary",
    summaryPlaceholder: "Describe your field, your experience, your core skills, and the value you bring.",
    summaryMeta: "Aim for 300–500 characters; 700 maximum.",
    steps: {
      basics: { label: "Your details", description: "The essentials a recruiter needs to recognise and contact you.", example: "Use a common job title, for example Cloud Engineer, not Cloud Ninja." },
      summary: { label: "Summary", description: "Sum up your skills, the context of your experience, and the value you bring.", example: "Aim for 3–4 sentences relevant to the role you want." },
      experience: { label: "Experience", description: "Lead with recent roles and results you can prove.", example: "Bullet formula: action verb + context + impact or measure." },
      education: { label: "Education", description: "Add the formal education that is most relevant.", example: "State the degree, field, institution, and period consistently." },
      skills: { label: "Skills", description: "Group hard skills so recruiters and ATS can scan them quickly.", example: "Example groups: Cloud, Automation, Observability, or Security." },
      extras: { label: "Extras", description: "Turn on the optional sections that genuinely support the target role.", example: "Projects and certifications usually beat a generic list of interests." },
    },
    basics: {
      fullName: { label: "Full name", placeholder: "Dina Pratama" },
      headline: { label: "Current / target job title", placeholder: "Cloud Engineer" },
      email: { label: "Email", placeholder: "name@example.com" },
      phone: { label: "Phone number", placeholder: "+62 812 3456 7890" },
      location: { label: "Location", placeholder: "Jakarta, Indonesia" },
    },
    collections: {
      links: {
        title: "Professional links", singular: "link", add: "Add link",
        fields: { label: { label: "Label", placeholder: "LinkedIn" }, url: { label: "URL", placeholder: "https://linkedin.com/in/name" } },
      },
      experience: {
        title: "Work experience", singular: "role", add: "Add role",
        fields: {
          role: { label: "Job title", placeholder: "Cloud Engineer" },
          organization: { label: "Company / organisation", placeholder: "Company name" },
          location: { label: "Location", placeholder: "Jakarta or Remote" },
          startDate: { label: "Start" },
          endDate: { label: "End" },
          current: { label: "I still work here" },
          bullets: { label: "Achievements and responsibilities", placeholder: "One bullet per line", help: "Start with the action, then the context and the impact that genuinely happened." },
        },
      },
      education: {
        title: "Education", singular: "qualification", add: "Add education",
        fields: {
          qualification: { label: "Degree / qualification", placeholder: "Bachelor of Computer Science" },
          field: { label: "Field of study", placeholder: "Computer Science" },
          institution: { label: "Institution", placeholder: "University name" },
          location: { label: "Location", placeholder: "Bandung" },
          startDate: { label: "Start" },
          endDate: { label: "End" },
          bullets: { label: "Relevant details", placeholder: "Achievements, focus areas, or relevant activities — one per line" },
        },
      },
      skills: {
        title: "Skill groups", singular: "skill group", add: "Add group",
        fields: {
          name: { label: "Group name", placeholder: "Cloud" },
          items: { label: "Skills", placeholder: "AWS, Amazon EKS, Terraform", help: "Separate with commas and list only skills you genuinely have." },
        },
      },
      projects: {
        title: "Projects", singular: "project", add: "Add project",
        fields: {
          name: { label: "Project name", placeholder: "AWS Landing Zone" },
          role: { label: "Role", placeholder: "Cloud Engineer" },
          startDate: { label: "Start" },
          endDate: { label: "End" },
          url: { label: "URL", placeholder: "https://…" },
          bullets: { label: "Contribution and outcome", placeholder: "One bullet per line", help: "Explain your contribution, the technology you used, and the outcome." },
        },
      },
      certifications: {
        title: "Certifications", singular: "certification", add: "Add certification",
        fields: {
          name: { label: "Certification name", placeholder: "AWS Certified Solutions Architect — Associate" },
          issuer: { label: "Issuer", placeholder: "Amazon Web Services" },
          date: { label: "Issued" },
          credentialId: { label: "Credential ID", placeholder: "Optional" },
          url: { label: "Verification URL", placeholder: "https://…" },
        },
      },
      languages: {
        title: "Languages", singular: "language", add: "Add language",
        fields: {
          name: { label: "Language", placeholder: "English" },
          proficiency: { label: "Level", placeholder: "Professional working proficiency" },
        },
      },
      awards: {
        title: "Awards", singular: "award", add: "Add award",
        fields: {
          title: { label: "Title", placeholder: "Employee Excellence Award" },
          issuer: { label: "Awarded by", placeholder: "Organisation name" },
          date: { label: "Date" },
          description: { label: "Notes", placeholder: "Why or in what context it was awarded" },
        },
      },
      volunteering: {
        title: "Volunteer experience", singular: "volunteer role", add: "Add volunteer role",
        fields: {
          role: { label: "Role", placeholder: "Cloud mentor" },
          organization: { label: "Organisation", placeholder: "Tech community" },
          startDate: { label: "Start" },
          endDate: { label: "End" },
          bullets: { label: "Contribution", placeholder: "One bullet per line" },
        },
      },
    },
    letter: {
      eyebrow: "Second document",
      title: "Cover Letter",
      intro: "The letter that accompanies your CV. It explains why you are applying and the experience most relevant to the target role.",
      tip: "Three paragraphs is enough: why you are applying, evidence with numbers, then a close. Avoid repeating the whole CV.",
      reusedTitle: "Reused, no need to type it twice",
      statusFilled: "Filled",
      statusMissing: "Missing",
      statusOptional: "Optional",
      fillNow: "Fill it now",
      signerLabel: "Name on the signature",
      signerHint: "Taken from the Your details step",
      roleLabel: "Role you are applying for",
      roleHint: "Set in the job-match panel",
      companyLabel: "Target company",
      companyHint: "Optional, set in the job-match panel",
      paragraphMeta: "{paragraphs} paragraphs · {words} words",
      lengthHint: "Aim for 200–350 words so it stays on one page.",
      bodyHelp: "One paragraph per line. Leave a blank line between them for readability.",
      fields: {
        recipient: { label: "Recipient", placeholder: "Hiring Team" },
        recipientTitle: { label: "Recipient's title", placeholder: "Optional, for example Talent Acquisition" },
        city: { label: "City", placeholder: "Jakarta" },
        date: { label: "Letter date", help: "Leave it empty if you prefer to write the date by hand when sending." },
        greeting: { label: "Greeting", placeholder: "Dear Hiring Manager," },
        closing: { label: "Closing", placeholder: "Sincerely," },
        paragraphs: { label: "Letter body" },
      },
      example: [
        "I am writing to apply for the Cloud Engineer role at your company.",
        "",
        "Over the past three years I have built and operated AWS platforms, including standardising deployment for 25 workloads through Terraform, which cut release time by 40%.",
        "",
        "I would be glad to discuss how this experience can support your technology goals. Thank you for your time and consideration.",
      ].join("\n"),
    },
  },
});

export function editorCopy(language = "id") {
  return EDITOR_COPY[language] ?? EDITOR_COPY.id;
}

export function fill(template, vars = {}) {
  return String(template).replace(/\{(\w+)\}/g, (match, name) => (name in vars ? String(vars[name]) : match));
}
